### PR TITLE
Add `memfence` before reading RDTSC

### PR DESCRIPTION
**Pull request by itzmeanjan**
Hi, 

I just added a memory load/ store fence before RDTSC is accessed for `x86` and `x86_64` targets.

### CODE REVIEW

**Comment by wainwrightmark** [comment]
Looks good. Just wondering if there's any argument to wrapping in LFence as well 
e.g. 
```
mfence()
lfence()
rdtsc()
lfence()
```

**Comment by itzmeanjan** [comment]
At least by the documentation https://doc.rust-lang.org/core/arch/x86_64/fn._mm_mfence.html, it seems `mfence` does the job of both `lfence` and `sfence`. So as I understand it, `mfence` should do the trick, but one might always be extra cautious - though I don't have any opinion if that's an overkill or not.

**Comment by itzmeanjan** [comment]
I found https://github.com/pornin/crrl/blob/73b33c1efc73d637f3084d197353991a22c10366/benches/util.rs#L5 where only `lfence` is used before issuing `rdtsc`, but I wanted to also stores to be visible, which is why I ended up using `mfence`.

**Comment by wainwrightmark** [comment]
> I found https://github.com/pornin/crrl/blob/73b33c1efc73d637f3084d197353991a22c10366/benches/util.rs#L5 where only `lfence` is used before issuing `rdtsc`, but I wanted to also stores to be visible, which is why I ended up using `mfence`.

That makes sense but my concern is that someone else might want a different fencing strategy. I want to support everyone and also avoid any breaking or value breaking changes if possible. 

How would you feel about my adding a new type `CyclesPerByte_MFence` that has this functionality? Another approach might be to use const generics. 

```rust
pub struct CyclesPerByteMeasurement<const MFENCE: bool, const LFENCE: bool>;
pub type CyclesPerByte = CyclesPerByteMeasurement::<false, false>;
```

**Comment by itzmeanjan** [comment]
> That makes sense but my concern is that someone else might want a different fencing strategy. I want to support everyone and also avoid any breaking or value breaking changes if possible.

Sure, but without a `fence` if one uses `RDTSC` then the result it produces it pretty much useless. `RDTSC` documentation says so @ https://doc.rust-lang.org/stable/core/arch/x86_64/fn._rdtsc.html. 

So I'd say keeping `mfence` before issuing `rdtsc` is **must**, but I'm thinking of keeping another `mfence` after `rdtsc` may not hurt - this is my understanding after reading `RDTSC` documentation. So it'll look like

```rust
mfence(); // Ensures all read/ writes to memory are visible
let res = _rdtsc();
mfence();  // Ensures RDTSC is issued first and then next instructions are issued, does it help though ?
// ...
```

> How would you feel about my adding a new type `CyclesPerByte_MFence` that has this functionality? Another approach might be to use const generics.

I won't do that.

**Comment by itzmeanjan** [comment]
Hi @wainwrightmark , I've added support for aarch64 targets, running GNU/Linux kernel @ 558b4a00f590093887b45ec7c7929808be2d4bb5.

**Comment by itzmeanjan** [comment]
And I found current way of using RDTSC (@ 2dc25c692a75b21f439e959bce55c04fe0f30fdc) is giving me fairly consistent results, when all cpu cores are governed by **performance** profile.

**Comment by wainwrightmark** [comment]
> Hi @wainwrightmark , I've added support for aarch64 targets, running GNU/Linux kernel @ [558b4a0](https://github.com/wainwrightmark/criterion-cycles-per-byte/commit/558b4a00f590093887b45ec7c7929808be2d4bb5).

This is great. I would be very happy to merge this as a separate pull request but I don't think it belongs in this one.


I think adding the memfence is probably correct for most users but my primary concern with this repository is to maintain compatibility and avoid breaking or value-breaking changes. Would it be possible to add a second type e.g. `CyclesPerByteMFenced` which has your code in it and leave the existing code alone. We can add documentation recommending it, but I would rather not break any existing users who are providing their own fencing strategy (e.g. using LFence).

**Comment by itzmeanjan** [comment]
> This is great. I would be very happy to merge this as a separate pull request but I don't think it belongs in this one.

Correct, I've sent https://github.com/wainwrightmark/criterion-cycles-per-byte/pull/4.

**Comment by itzmeanjan** [comment]
> I think adding the memfence is probably correct for most users but my primary concern with this repository is to maintain compatibility and avoid breaking or value-breaking changes. Would it be possible to add a second type e.g. `CyclesPerByteMFenced` which has your code in it and leave the existing code alone. We can add documentation recommending it, but I would rather not break any existing users who are providing their own fencing strategy (e.g. using LFence).

With the way it's currently kept (just issuing RDTSC without any sort of barriers) the numbers you get are pretty misleading and probably wrong. Also users of this library won't be able to add a barrier before CPU cycles are captured, I advice we just stick to adding a read/ write barrier before we issue the RDTSC instruction. If you agree to this, I can clean up this PR and publish it.

**Comment by itzmeanjan** [comment]
Now that #4 is merged, I can clean up this PR and merge it so that we can release it on crates.io.

**Comment by itzmeanjan** [comment]
@wainwrightmark this PR has changes from merged PR #4, we can consider 

- merging this PR
- bump version 
- release on crates.io

Which should give users of this library with correct numbers on x86{_64} targets.

**Comment by wainwrightmark** [comment]
I have merged this. Thanks for the contribution. I will do a version bump to 0.6 and release to crates.io shortly.

**Comment by itzmeanjan** [comment]
> I have merged this. Thanks for the contribution. I will do a version bump to 0.6 and release to crates.io shortly.

Thank you very much @wainwrightmark :pray:

**Pull request merged**
